testexe: main.cpp window.cpp
	g++ -o testexe main.cpp window.cpp -I/usr/local/Cellar/glfw/3.3.3 -I/usr/local/Cellar/glew/2.2.0_1 -I/usr/local/include -L/usr/local/lib/ -L/usr/local/Cellar/glfw/3.3.3/lib -L/usr/local/Cellar/glew/2.2.0_1/lib  -lGLEW -lglfw -framework OpenGL

